// https://docs.groovy-lang.org/latest/html/documentation/
// library 'jctest'
GIT_LOCATION="https://github.com/MindStrongHealth/jctest.git"
SLACK_CHANNEL="#jc-testing"
BRANCH=env.BRANCH_NAME
releaseVersion=""

@NonCPS
def getBuildUser() {
  return currentBuild.rawBuild.getCause(Cause.UserIdCause)?.getUserId()
}

@NonCPS
def sendSuccessSlackNotification (releaseVersion) {
  slackSend channel: SLACK_CHANNEL, color: 'good', message: "Job Name - ${env.JOB_NAME} \n Build URL - ${env.BUILD_URL} \nRelease Tag - ${releaseVersion} \nStatus - *`Success`*"
}

@NonCPS
def sendFailureSlackNotification (currentStep, errorMsg) {
  slackSend channel: SLACK_CHANNEL, color: 'danger', message: "Job Name - ${env.JOB_NAME}\n Build URL - ${env.BUILD_URL}console \n Failed at step - ${currentStep} \nStatus - *`Failed`* \n Exception-${errorMsg}"
}

node {

  checkout scm;
  println getBuildUser()
    load '.jenkins/Jenkinsfile.common';

  if (getBuildUser() != null){
    load '.jenkins/Jenkinsfile.manual'
  } else {
    load '.jenkins/Jenkinsfile.auto'
  }
}
