// https://docs.groovy-lang.org/latest/html/documentation/
// library 'jctest'
node {

  checkout scm;
  println getBuildUser()
    load '.jenkins/Jenkinsfile.common';

  if (getBuildUser() != null){
    load '.jenkins/Jenkinsfile.manual'
  } else {
    load '.jenkins/Jenkinsfile.auto'
  }
}
